routes/admin.php
<?php

// Admin routes

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\LandingPageController;

Route::middleware('guest')->group(function () {
    Route::get('login', [AuthController::class, 'showLoginForm'])->name('login');
    Route::post('login', [AuthController::class, 'login']);

    Route::get('register', [AuthController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [AuthController::class, 'register']);
});
Route::post('logout', [AuthController::class, 'logout'])->name('logout')->middleware('auth:web');

Route::middleware('auth:web')->name('admin.')->group(function () {
    Route::get('/', [LandingPageController::class, 'index'])->name('dashboard');

    Route::prefix('landing')->name('landing.')->group(function () {
        Route::post('/', [LandingPageController::class, 'store'])->name('store');
        Route::put('/', [LandingPageController::class, 'update'])->name('update');
    });
});

routes/web.php
<?php

use App\Http\Controllers\LandingPageHandlerController;
use Illuminate\Support\Facades\Route;

Route::get('/', [LandingPageHandlerController::class, 'index']);

app/Models/Domain.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    public $timestamps = false;

    protected $fillable = ['host'];

    public function scopeFree(Builder $q)
    {
        $q->whereNull('user_id');
    }

    public function isFree(): bool
    {
        return is_null($this->user_id);
    }
}

app/Models/LandingPage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class LandingPage extends Model
{
    protected $fillable = [
        'title',
        'sub_title',
        'img_path',
        'content',
        'domain_id',
        'template',
    ];

    public function domain()
    {
        return $this->belongsTo(Domain::class);
    }

    public static function findByHost(string $host)
    {
        return self::query()
                   ->whereHas('domain', function (Builder $q) use ($host) {
                       $q->where('host', $host);
                   })
                   ->first();
    }
}

app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    public $timestamps = false;
}

app/Models/Template.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Template extends Model
{
    public $timestamps = false;

    protected $fillable = ['content'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
        'birth_date',
        'avatar_url',
    ];

    protected $hidden = [
        'password',
    ];

    protected $casts = [
        'birth_date' => 'date',
    ];

    public function domain()
    {
        return $this->hasOne(Domain::class);
    }

    public function landing_page()
    {
        return $this->hasOneThrough(LandingPage::class, Domain::class);
    }

    public function setDomain(int $domainId)
    {
        Domain::query()->whereKey($domainId)->update(['user_id' => auth()->id()]);
    }
}

app/Http/Controllers/Admin/AuthController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\FileUploadHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\LoginRequest;
use App\Http\Requests\Admin\RegisterRequest;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;

class AuthController extends Controller
{
    public function showLoginForm()
    {
        return view('auth.login');
    }

    public function login(LoginRequest $request)
    {
        if (Auth::attempt($request->only(['email', 'password']))) {
            return \Redirect::route('admin.dashboard');
        }
        throw ValidationException::withMessages([
            'email' => 'Password is wrong'
        ]);
    }

    public function showRegistrationForm()
    {
        return view('auth.register');
    }

    public function register(RegisterRequest $request)
    {
        $data = $request->validated();
        $data['avatar_url'] = FileUploadHelper::uploadFileOrReturnPath($data['avatar_url'], 'avatar');
        $data['password'] = \Hash::make($request->get('password'));

        $user = User::create($data);

        Auth::loginUsingId($user->id);

        return \Redirect::route('admin.dashboard');
    }

    public function logout()
    {
        Auth::logout();

        return \Redirect::route('login');
    }
}

app/Http/Controllers/Admin/LandingPageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Actions\GetTemplatesPathsAction;
use App\Actions\StoreLandingAction;
use App\Actions\UpdateLandingAction;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreLandingPageRequest;
use App\Http\Requests\Admin\UpdateLandingPageRequest;
use App\Models\Domain;

class LandingPageController extends Controller
{
    public function index()
    {
        $landing = auth()->user()->landing_page;
        $templates = app(GetTemplatesPathsAction::class)->run();

        if ($landing) {
            return view('admin.landing.edit', [
                'landing'   => $landing,
                'templates' => $templates,
            ]);
        }

        return view('admin.landing.create', [
            'domains'   => $landing ? [] : Domain::free()->get(),
            'templates' => $templates,
        ]);
    }

    public function store(StoreLandingPageRequest $request)
    {
        app(StoreLandingAction::class)->run($request->validated());

        return \Redirect::route('admin.dashboard');
    }

    public function update(UpdateLandingPageRequest $request)
    {
        app(UpdateLandingAction::class)->run($request->validated());

        return \Redirect::route('admin.dashboard');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LandingPageHandlerController.php
<?php

namespace App\Http\Controllers;

use App\Models\LandingPage;
use Illuminate\Http\Request;

class LandingPageHandlerController extends Controller
{
    public function index(Request $request)
    {
        $landing = LandingPage::findByHost($request->getHost());

        if (!$landing) {
            return response("There is no landing yet");
        }
        return view('admin.templates.' . $landing->template, [
            'landing' => $landing
        ]);
    }
}

resources/views/admin/landing/create.blade.php
@extends('adminlte::page')

@section('title') Create landing @endsection

@section('plugins.Summernote', true)
@section('plugins.BsCustomFileInput', true)

@section('content')
    @if(count($domains) == 0)
        There is no available domains
    @else
        <form action="{{route('admin.landing.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <x-adminlte-select name="domain_id" label="Domain">
                @foreach($domains as $domain)
                    <option value="{{$domain->id}}">{{$domain->host}}</option>
                @endforeach
            </x-adminlte-select>

            <x-adminlte-select name="template" label="Template">
                @foreach($templates as $template)
                    <option value="{{$template}}">{{$template}}</option>
                @endforeach
            </x-adminlte-select>

            <x-adminlte-input name="title" label="Title"/>

            <x-adminlte-input name="sub_title" label="Sub title"/>

            <x-adminlte-input-file name="img_path" label="Image"/>

            <x-adminlte-text-editor name="content">
                <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit.
                <br>
                <i>Aliquam quis nibh massa.</i>
            </x-adminlte-text-editor>

            <x-adminlte-button label="Create" type="submit"/>
        </form>
    @endif
@endsection

resources/views/admin/landing/edit.blade.php
@extends('adminlte::page')

@section('title') Edit landing @endsection

@section('plugins.Summernote', true)
@section('plugins.BsCustomFileInput', true)

@section('content')
    <form action="{{route('admin.landing.update')}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')

        <x-adminlte-input name="domain_id" disabled label="Domain" value="{{$landing->domain->host}}"/>
        <x-adminlte-select name="template" label="Template">
            @foreach($templates as $template)
                <option value="{{$template}}"
                        @if($template == $landing->template) selected @endif
                >{{$template}}</option>
            @endforeach
        </x-adminlte-select>

        <x-adminlte-input name="title" label="Title" value="{{$landing->title}}"/>

        <x-adminlte-input name="sub_title" label="Sub title" value="{{$landing->sub_title}}"/>

        <x-adminlte-input-file name="img_path" label="Image" placeholder="{{$landing->img_path}}"/>

        <x-adminlte-text-editor name="content">
            {!! $landing->content !!}
        </x-adminlte-text-editor>

        <x-adminlte-button label="Update" type="submit"/>
    </form>
@endsection

resources/views/admin/templates/template-1.blade.php
<html>
<head>
    <title>{{ $landing->title }}</title>
</head>
<body>
<h1>Template 1</h1>

<h2>{{ $landing->sub_title }}</h2>

<img src="{{ $landing->img_path }}" height="200">

<div style="border: solid 2px; padding: 10px">
    {!! $landing->content !!}
</div>
</body>
</html>

resources/views/admin/templates/template-2.blade.php
<html>
<head>
    <title>{{ $landing->title }}</title>
</head>
<body>
<h1>Template 2</h1>

<h2>{{ $landing->sub_title }}</h2>

<img src="{{ $landing->img_path }}" height="300">

<div style="border: dotted 4px; padding: 20px">
    {!! $landing->content !!}
</div>
</body>
</html>

resources/views/admin/templates/template-3.blade.php
<html>
<head>
    <title>{{ $landing->title }}</title>
</head>
<body>
<h1>Template 3</h1>

<h2>{{ $landing->sub_title }}</h2>

<img src="{{ $landing->img_path }}" height="400">

<div>
    {!! $landing->content !!}
</div>
</body>
</html>